apiVersion: v2
name: sda-db
version: "0.5.2"
description: Database component for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sda-helm
