apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}
data:
  password_hash: {{ (required "A valid MQ password hash is required" .Values.config.adminPasswordHash) | quote | trimall "\"" | b64enc }}
  {{- if and .Values.config.shovel.host (and .Values.config.shovel.user .Values.config.shovel.pass) }}
  shovel_connection: {{ printf "amqps://%s:%s@%s:%s/%s?server_name_indication=%s" .Values.config.shovel.user .Values.config.shovel.pass (required "A valid MQ shovel host is required" .Values.config.shovel.host) ( .Values.config.shovel.port | quote | trimall "\"" ) .Values.config.shovel.vhost .Values.config.shovel.host | quote | trimall "\"" | b64enc }}
  {{- end }}
