{{- if and (not .Values.global.confFile) (or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType)) (not .Values.global.deploymentType)) }}
{{- if .Values.global.ingress.deploy }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sda.fullname" . }}-doa-ingress
  labels:
    app: {{ template "sda.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.global.ingress.labels }}
{{ toYaml .Values.global.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if .Values.global.ingress.issuer }}
    certmanager.io/cluster-issuer: {{ .Values.global.ingress.issuer | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ required "An ingress hostname is required!" .Values.global.ingress.hostName.doa }}
    http:
      paths:
        - path: "/"
          backend:
            serviceName: {{ template "sda.fullname" . }}-doa
            servicePort: {{ .Values.doa.servicePort }}
  tls:
  - hosts:
    - {{ required "An ingress hostname is required!" .Values.global.ingress.hostName.doa }}
    secretName: {{ if .Values.global.ingress.secretNames.doa }}{{ .Values.global.ingress.secretNames.doa }}{{- else }}"{{ template "sda.fullname" . }}-ingress-doa"{{- end }}
{{- end }}
{{- end }}
