{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if not .Values.global.noTLS }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-doa
  labels:
    app: {{ template "sda.fullname" . }}-doa
spec:
  ports:
  - name: doa
    port: 443
    targetPort: doa
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-doa
{{- end }}
{{- end }}
