{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-ingest
type: Opaque
data:
  c4ghPassphrase: {{ .Values.global.c4gh.passphrase | b64enc }}
  dbPassword: {{ include "dbPassIngest" . | b64enc }}
  dbUser: {{ include "dbUserIngest" . | b64enc }}
  mqPassword: {{ include "mqPassIngest" . | b64enc }}
  mqUser: {{ include "mqUserIngest" . | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $ingest := .Files.Glob "files/ingest*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-ingest-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $ingest ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
